# Generated by Django 3.2.7 on 2021-09-26 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
