# Generated by Django 3.2.7 on 2021-09-23 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0003_auto_20210805_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='end_supsension',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='onetime_pickup',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='pickup_day',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='start_supsension',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='suspended',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='customer',
            name='zip_code',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
