# Generated by Django 3.2.7 on 2021-09-27 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_emergency_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='emergency_form',
        ),
    ]
