# Generated by Django 3.2.7 on 2021-09-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_remove_customer_emergency_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='emergency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
