# Generated by Django 3.2.7 on 2021-10-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='hours',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
